package com.khabar.api.audit;

public enum AuditAction {
    VIEWED_RECORD,
    CALLED_ABOUT_REPLY,
    OVERRODE_SAFETY_FINDING,
    VIEWED_SUMMARY,
    VIEWED_MEDICATIONS,
    VIEWED_INTAKE,
    VIEWED_PREVISIT,
    VIEWED_READINGS
}
