"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import Link from "next/link"
import { AlertTriangle, ArrowRight, CalendarDays, Check, HeartPulse, Plus, RefreshCw, Search, UserPlus, UsersRound } from "lucide-react"
import { apiRequest } from "@/lib/api"
import type { Appointment, CallList, Me, Patient } from "@/lib/types"
import { EmptyState, SectionHeading, StatusBadge } from "@/components/ui"
import { ClinicTools } from "@/components/clinical/clinic-tools"
import styles from "@/app/home/home.module.css"

type Notice={tone:"error"|"success"|"info";text:string}

export function DoctorHome({me,notify}:{me:Me;notify:(notice:Notice|null)=>void}){
  const [calls,setCalls]=useState<CallList|null>(null);const [patients,setPatients]=useState<Patient[]>([]);const [appointments,setAppointments]=useState<Appointment[]>([]);const [query,setQuery]=useState("");const [busy,setBusy]=useState<string|null>(null);const [showAdd,setShowAdd]=useState(false);const [newPatient,setNewPatient]=useState({fullName:"",icNumber:"",phone:"",preferredLanguage:"en"});const [invite,setInvite]=useState<string|null>(null)
  const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Kuala_Lumpur"}).format(new Date())
  const load=useCallback(async()=>{try{const [nextCalls,nextPatients,nextAppointments]=await Promise.all([apiRequest<CallList>("/api/clinic/call-list"),apiRequest<Patient[]>("/api/clinic/patients"),apiRequest<Appointment[]>(`/api/clinic/appointments?date=${today}`)]);setCalls(nextCalls);setPatients(nextPatients);setAppointments(nextAppointments)}catch(error){notify({tone:"error",text:error instanceof Error?error.message:"Clinic information could not be loaded."})}},[notify,today])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
  const visible=useMemo(()=>patients.filter(p=>p.fullName.toLowerCase().includes(query.toLowerCase())||p.icMasked.toLowerCase().includes(query.toLowerCase())),[patients,query])
  async function markCalled(patientId:string){setBusy(patientId);try{await apiRequest(`/api/clinic/call-list/${patientId}/called`,{method:"POST"});notify({tone:"success",text:"The call was recorded in the patient access log."});await load()}catch(error){notify({tone:"error",text:error instanceof Error?error.message:"The call could not be recorded."})}finally{setBusy(null)}}
  async function addPatient(event:React.FormEvent){event.preventDefault();setBusy("patient");try{const result=await apiRequest<{inviteCode:string}>("/api/clinic/patients",{method:"POST",body:JSON.stringify({...newPatient,allergies:[],pregnant:false})});setInvite(result.inviteCode);setNewPatient({fullName:"",icNumber:"",phone:"",preferredLanguage:"en"});await load();notify({tone:"success",text:"The patient record is ready. Share the one-time code securely."})}catch(error){notify({tone:"error",text:error instanceof Error?error.message:"The patient could not be added."})}finally{setBusy(null)}}
  const hour=new Date().getHours();const greeting=hour<12?"Good morning":hour<18?"Good afternoon":"Good evening"
  return <main className={styles.workspace} id="overview"><section className={styles.workspaceIntro}><div><p>{new Intl.DateTimeFormat("en-MY",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}</p><h1>{greeting}, {me.displayName.split(" ")[0]}.</h1><span>Start with the people who need a human response.</span></div><button className="button-primary" onClick={()=>setShowAdd(true)}><UserPlus size={17}/>Add patient</button></section>
    <section className={styles.metricStrip} aria-label="Today's clinic summary"><div className={styles.urgentMetric}><span><AlertTriangle size={17}/>Call now</span><strong>{calls?.counts.red??"—"}</strong><small>Urgent replies and readings</small></div><div><span><HeartPulse size={17}/>Check today</span><strong>{calls?.counts.watch??"—"}</strong><small>Needs a closer look</small></div><div><span><CalendarDays size={17}/>Appointments</span><strong>{appointments.length||"—"}</strong><small>On today’s schedule</small></div><div><span><UsersRound size={17}/>In follow-up</span><strong>{calls?.patientsInFollowUp??"—"}</strong><small>Across the clinic</small></div></section>
    <div className={styles.dashboardGrid}><section className={styles.priorityCard}><SectionHeading eyebrow="Live priority" title="Who needs you first" action={<button className="button-quiet" onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button>}/>{calls?.items.length?calls.items.slice(0,6).map((item,index)=><article className={styles.priorityRow} key={item.patientId}><span className={`${styles.rank} ${styles[`rank${item.level}`]}`}>{String(index+1).padStart(2,"0")}</span><div className={styles.personCell}><strong>{item.fullName}</strong><span>{item.preferredLanguage.toUpperCase()} · {item.followUpDay?`day ${item.followUpDay}`:"new follow-up"}</span></div><div className={styles.reasonCell}><StatusBadge level={item.level}>{item.reason.replaceAll("_"," ").toLowerCase()}</StatusBadge><p>{item.urgentReply||item.latestReply||"No reply for 48 hours."}</p></div><button className="button-secondary" disabled={busy===item.patientId} onClick={()=>void markCalled(item.patientId)}>{busy===item.patientId?"Saving…":"Mark called"}</button></article>):<EmptyState icon={<Check size={20}/>} title="The call list is clear" copy="New concerning replies and readings will appear here automatically."/>}</section>
      <aside className={styles.todayCard} id="schedule"><SectionHeading eyebrow="Today" title="Clinic rhythm"/><div className={styles.scheduleList}>{appointments.length?appointments.slice(0,5).map(item=><div key={item.id}><span>{item.time}</span><i/><div><strong>{item.fullName||"Booked patient"}</strong><small>{item.reason||"Consultation"}</small></div></div>):<div className={styles.noVisits}><span><CalendarDays size={18}/></span><div><strong>No visits today</strong><p>The day is open. Patient bookings will appear here.</p></div></div>}</div><div className={styles.followupSignal}><span><HeartPulse size={18}/></span><div><strong>{calls?.patientsInFollowUp??0} active follow-ups</strong><p>Khabar is watching replies, missed doses and home readings.</p></div></div></aside>
    </div>
    <section className={styles.peopleCard} id="people"><SectionHeading eyebrow="Clinic directory" title="People in your care" action={<div className={styles.search}><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search patients" aria-label="Search patients"/></div>}/><div className={styles.peopleTable}><div className={styles.tableHead}><span>Patient</span><span>Language</span><span>Follow-up</span><span>Account</span><span/></div>{visible.slice(0,12).map(patient=><div className={styles.tableRow} key={patient.id}><div><span className={styles.avatar}>{initials(patient.fullName)}</span><p><strong>{patient.fullName}</strong><small>{patient.icMasked}</small></p></div><span>{patient.preferredLanguage.toUpperCase()}</span><span>{patient.followUpDay?`Day ${patient.followUpDay}`:"Not started"}</span><StatusBadge level={patient.hasAccount?"ok":"review"}>{patient.hasAccount?"Linked":"Invite pending"}</StatusBadge><Link href={`/home/patients/${patient.id}`}>Open <ArrowRight size={14}/></Link></div>)}</div></section>
    {showAdd&&<div className={styles.modalBackdrop} role="presentation"><section className={styles.modal} role="dialog" aria-modal="true" aria-labelledby="add-patient-title"><div className={styles.modalHead}><div><p>Clinic onboarding</p><h2 id="add-patient-title">Add a patient</h2></div><button onClick={()=>{setShowAdd(false);setInvite(null)}} aria-label="Close">×</button></div>{invite?<div className={styles.inviteSuccess}><span><Check size={22}/></span><h3>Patient record created</h3><p>Share this one-time code securely. It expires in seven days.</p><strong>{invite}</strong><button className="button-primary" onClick={()=>{void navigator.clipboard.writeText(invite);notify({tone:"success",text:"Invitation code copied."})}}>Copy code</button></div>:<form className={styles.modalForm} onSubmit={addPatient}><label>Full name<input value={newPatient.fullName} onChange={e=>setNewPatient({...newPatient,fullName:e.target.value})} required/></label><div className={styles.twoFields}><label>IC number<input value={newPatient.icNumber} onChange={e=>setNewPatient({...newPatient,icNumber:e.target.value})}/></label><label>Phone<input value={newPatient.phone} onChange={e=>setNewPatient({...newPatient,phone:e.target.value})}/></label></div><label>Preferred language<select value={newPatient.preferredLanguage} onChange={e=>setNewPatient({...newPatient,preferredLanguage:e.target.value})}><option value="en">English</option><option value="ms">Bahasa Melayu</option><option value="zh">中文</option><option value="ta">தமிழ்</option></select></label><div className={styles.modalActions}><button type="button" className="button-secondary" onClick={()=>setShowAdd(false)}>Cancel</button><button className="button-primary" disabled={busy==="patient"}>{busy==="patient"?"Creating…":<><Plus size={16}/>Create record</>}</button></div></form>}</section></div>}
    <ClinicTools notify={notice=>notify(notice)}/>
  </main>
}

function initials(name:string){return name.split(" ").slice(0,2).map(part=>part[0]).join("").toUpperCase()}
