"use client"

import { useCallback, useEffect, useState } from "react"
import { BookOpenCheck, Check, Copy, Plus, UserPlus } from "lucide-react"
import { apiRequest } from "@/lib/api"
import type { ApprovedAnswer } from "@/lib/types"
import { EmptyState, SectionHeading } from "@/components/ui"
import styles from "@/app/home/clinical.module.css"

type Notice={tone:"error"|"success"|"info";text:string}

export function ClinicTools({notify}:{notify:(notice:Notice)=>void}){
  const [answers,setAnswers]=useState<ApprovedAnswer[]>([]);const [doctorCode,setDoctorCode]=useState<string|null>(null);const [busy,setBusy]=useState<string|null>(null);const [retiring,setRetiring]=useState<string|null>(null);const [form,setForm]=useState({title:"",triggers:"",en:"",ms:"",zh:"",ta:""})
  const load=useCallback(async()=>{try{setAnswers(await apiRequest<ApprovedAnswer[]>("/api/clinic/answers"))}catch(error){notify({tone:"error",text:error instanceof Error?error.message:"Approved answers could not be loaded."})}},[notify])
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load])
  async function inviteDoctor(){setBusy("doctor");try{const result=await apiRequest<{inviteCode:string}>("/api/clinic/doctor-invites",{method:"POST"});setDoctorCode(result.inviteCode);notify({tone:"success",text:"A one-time colleague invitation is ready."})}catch(error){notify({tone:"error",text:error instanceof Error?error.message:"The invitation could not be created."})}finally{setBusy(null)}}
  async function addAnswer(event:React.FormEvent){event.preventDefault();setBusy("answer");try{await apiRequest("/api/clinic/answers",{method:"POST",body:JSON.stringify({title:form.title,triggers:form.triggers.split(",").map(v=>v.trim()).filter(Boolean),texts:{en:form.en,ms:form.ms,zh:form.zh,ta:form.ta}})});setForm({title:"",triggers:"",en:"",ms:"",zh:"",ta:""});await load();notify({tone:"success",text:"The clinic-approved answer is now available to follow-up triage."})}catch(error){notify({tone:"error",text:error instanceof Error?error.message:"The answer could not be saved."})}finally{setBusy(null)}}
  async function retire(id:string){setBusy(id);try{await apiRequest(`/api/clinic/answers/${id}`,{method:"DELETE"});setRetiring(null);await load();notify({tone:"success",text:"The answer was retired and preserved in the audit history."})}catch(error){notify({tone:"error",text:error instanceof Error?error.message:"The answer could not be retired."})}finally{setBusy(null)}}
  return <section className={styles.clinicTools} id="privacy"><div className={styles.toolsHead}><div><p>Clinic controls</p><h2>Trusted words and trusted people</h2></div><div>{doctorCode?<div className={styles.doctorCode}><small>Colleague code</small><strong>{doctorCode}</strong><button onClick={()=>void navigator.clipboard.writeText(doctorCode)} aria-label="Copy doctor invitation"><Copy size={15}/></button></div>:<button className="button-secondary" disabled={busy==="doctor"} onClick={()=>void inviteDoctor()}><UserPlus size={16}/>Invite a doctor</button>}</div></div><div className={styles.toolsGrid}><div className={styles.answerLibrary}><SectionHeading eyebrow="Follow-up knowledge" title="Approved answers"/>{answers.length?answers.map(answer=><article key={answer.id}><span><BookOpenCheck size={17}/></span><div><strong>{answer.title}</strong><small>{answer.triggers.join(" · ")}</small><p>{answer.texts.en||answer.texts.ms}</p></div>{retiring===answer.id?<div className={styles.retireConfirm}><button className="button-quiet" onClick={()=>setRetiring(null)}>Keep</button><button className="button-danger" disabled={busy===answer.id} onClick={()=>void retire(answer.id)}>Confirm</button></div>:<button className="button-quiet" onClick={()=>setRetiring(answer.id)}>Retire</button>}</article>):<EmptyState title="No approved answers" copy="Add wording the clinic has reviewed. Khabar can only reply using this library."/>}</div><form className={styles.answerForm} onSubmit={addAnswer}><SectionHeading eyebrow="Add to the library" title="New approved answer"/><label>Internal title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Mild nausea" required/></label><label>Trigger phrases<input value={form.triggers} onChange={e=>setForm({...form,triggers:e.target.value})} placeholder="nausea, loya, feel sick" required/></label><label>English answer<textarea value={form.en} onChange={e=>setForm({...form,en:e.target.value})} rows={3} required/></label><label>Bahasa Melayu answer<textarea value={form.ms} onChange={e=>setForm({...form,ms:e.target.value})} rows={3}/></label><details><summary>Chinese and Tamil translations</summary><label>Chinese<textarea value={form.zh} onChange={e=>setForm({...form,zh:e.target.value})} rows={2}/></label><label>Tamil<textarea value={form.ta} onChange={e=>setForm({...form,ta:e.target.value})} rows={2}/></label></details><button className="button-primary" disabled={busy==="answer"}>{busy==="answer"?"Saving…":<><Plus size={16}/>Approve answer</>}</button><p><Check size={14}/>The answer is attributed to the signed-in doctor.</p></form></div></section>
}
