"use client"

import { useEffect, useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { Activity, ArrowLeft, Check, HeartPulse, Link2, LoaderCircle, MessageCircle, Pill, ShieldCheck, Stethoscope, UserRound } from "lucide-react"
import { apiRequest } from "@/lib/api"
import { clearToken, getToken } from "@/lib/session"
import type { AccessLog, Me, Medication, Patient, Previsit, Reading } from "@/lib/types"
import { AppShell } from "@/components/home/app-shell"
import { EmptyState, SectionHeading, StatusBadge, Toast } from "@/components/ui"
import styles from "@/app/home/clinical.module.css"

export function PatientRecord({patientId}:{patientId:string}){
  const router=useRouter();const [me,setMe]=useState<Me|null>(null);const [patient,setPatient]=useState<Patient|null>(null);const [previsit,setPrevisit]=useState<Previsit|null>(null);const [meds,setMeds]=useState<Medication[]>([]);const [readings,setReadings]=useState<Reading[]>([]);const [log,setLog]=useState<AccessLog[]>([]);const [device,setDevice]=useState("");const [busy,setBusy]=useState<string|null>(null);const [notice,setNotice]=useState<{tone:"error"|"success"|"info";text:string}|null>(null)
  useEffect(()=>{const token=getToken();if(!token){router.replace("/login");return}Promise.all([apiRequest<Me>("/api/me"),apiRequest<Patient>(`/api/patients/${patientId}`),apiRequest<Previsit>(`/api/patients/${patientId}/previsit`).catch(()=>null),apiRequest<Medication[]>(`/api/patients/${patientId}/medications`),apiRequest<Reading[]>(`/api/patients/${patientId}/readings`),apiRequest<AccessLog[]>(`/api/patients/${patientId}/access-log`)]).then(([profile,person,pv,nextMeds,nextReadings,nextLog])=>{if(profile.role!=="DOCTOR")throw new Error("This clinical record is available to the clinic team only.");setMe(profile);setPatient(person);setPrevisit(pv);setMeds(nextMeds);setReadings(nextReadings);setLog(nextLog)}).catch(error=>setNotice({tone:"error",text:error instanceof Error?error.message:"The record could not be opened."}))},[patientId,router])
  function signOut(){clearToken();router.replace("/login")}
  async function startVisit(){setBusy("visit");try{const encounter=await apiRequest<{id:string}>(`/api/patients/${patientId}/encounters`,{method:"POST"});router.push(`/home/visits/${encounter.id}`)}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"The visit could not be started."});setBusy(null)}}
  async function linkDevice(event:React.FormEvent){event.preventDefault();setBusy("device");try{await apiRequest(`/api/patients/${patientId}/device`,{method:"PUT",body:JSON.stringify({deviceId:device.trim()})});setNotice({tone:"success",text:"The home device is now linked to this patient."});setDevice("")}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"The device could not be linked."})}finally{setBusy(null)}}
  if(!me||!patient)return <main className={styles.clinicalLoading}><LoaderCircle size={24}/><p>{notice?.text||"Opening the patient record…"}</p><Link className="button-secondary" href="/home">Back to home</Link></main>
  const report=previsit?.intake?.report
  return <AppShell me={me} onSignOut={signOut}>{notice&&<Toast tone={notice.tone} onClose={()=>setNotice(null)}>{notice.text}</Toast>}<main className={styles.record}><div className={styles.recordTop}><Link href="/home"><ArrowLeft size={16}/>Back to clinic</Link><button className="button-primary" disabled={busy==="visit"} onClick={()=>void startVisit()}><Stethoscope size={17}/>{busy==="visit"?"Starting…":"Start today’s visit"}</button></div><section className={styles.patientIdentity}><div className={styles.patientAvatar}><UserRound size={26}/></div><div><p>Patient record · access logged</p><h1>{patient.fullName}</h1><span>{patient.icMasked} · {patient.preferredLanguage.toUpperCase()} · {patient.clinicName}</span></div><div className={styles.identityTrust}><ShieldCheck size={17}/><span><strong>Verified record</strong>Your view is in the audit history.</span></div></section>
    <div className={styles.clinicalGrid}><section className={styles.previsitCard}><SectionHeading eyebrow="Before the consultation" title="The story so far"/>{previsit?<><div className={styles.flagRow}>{[...(previsit.patient.allergies||[]),...(report?.allergies||[])].filter((v,i,a)=>a.indexOf(v)===i).map(item=><StatusBadge key={item} level="red">Allergy: {item}</StatusBadge>)}{previsit.patient.pregnant&&<StatusBadge level="watch">Pregnant</StatusBadge>}</div><article className={styles.reasonBlock}><MessageCircle size={19}/><div><small>Reason for visit</small><blockquote>{report?.reason||"No completed intake. Ask the patient directly."}</blockquote></div></article>{report?.redFlags?.length?<div className={styles.warningList}>{report.redFlags.map((flag,index)=><p key={index}><HeartPulse size={16}/><span><strong>{flag.level==="red"?"Emergency sign mentioned":"Worth asking about"}</strong>{flag.matched}</span></p>)}</div>:null}<div className={styles.contextColumns}><div><h3>Last visit</h3>{previsit.lastVisit?<><strong>{previsit.lastVisit.diagnosis||"No diagnosis written"}</strong><p>{previsit.lastVisit.plan}</p><small>{new Intl.DateTimeFormat("en-MY",{dateStyle:"medium"}).format(new Date(previsit.lastVisit.finalisedAt))} · {previsit.lastVisit.doctor}</small></>:<p>First visit with Khabar.</p>}</div><div><h3>Recent replies</h3>{previsit.recentReplies.length?previsit.recentReplies.slice(0,3).map((reply,index)=><p key={index}>“{reply.text}” <StatusBadge level={reply.level}>{reply.level}</StatusBadge></p>):<p>No follow-up replies.</p>}</div></div></>:<EmptyState title="No pre-visit report" copy="The patient has not completed an intake yet. Continue with direct history taking."/>}</section>
      <aside className={styles.recordSide}><section><SectionHeading eyebrow="Current list" title="Medicines & remedies"/><div className={styles.compactClinicalList}>{meds.map(med=><div key={med.id}><Pill size={16}/><span><strong>{med.name}</strong><small>{med.kind==="HERB"?"Herb or remedy":"Medicine"} · {med.source||"source unknown"}</small></span></div>)}{!meds.length&&<p>Nothing listed yet.</p>}</div></section><section><SectionHeading eyebrow="Home monitoring" title="Latest readings"/><div className={styles.compactClinicalList}>{readings.slice(0,4).map(reading=><div key={reading.id}><Activity size={16}/><span><strong>{reading.description}</strong><small>{new Intl.DateTimeFormat("en-MY",{dateStyle:"medium"}).format(new Date(reading.measuredAt))}</small></span><StatusBadge level={reading.level}>{reading.level}</StatusBadge></div>)}{!readings.length&&<p>No home readings.</p>}</div></section><section><SectionHeading eyebrow="Favoriot" title="Link a home device"/><form className={styles.deviceForm} onSubmit={linkDevice}><label>Developer device ID<input value={device} onChange={e=>setDevice(e.target.value)} placeholder="Device identifier" required/></label><button className="button-secondary" disabled={busy==="device"}><Link2 size={15}/>Link device</button></form></section></aside>
    </div><section className={styles.auditCard}><SectionHeading eyebrow="Privacy" title="Record access history"/><div className={styles.auditTimeline}>{log.slice(0,10).map((entry,index)=><div key={`${entry.at}-${index}`}><span><Check size={14}/></span><p><strong>{entry.actor}</strong><small>{entry.action.replaceAll("_"," ").toLowerCase()} · {new Intl.DateTimeFormat("en-MY",{dateStyle:"medium",timeStyle:"short"}).format(new Date(entry.at))}</small></p></div>)}</div></section>
  </main></AppShell>
}
