"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { AlertTriangle, ArrowLeft, Check, CheckCircle2, FileText, HeartPulse, LoaderCircle, Mic, ShieldAlert, Sparkles, Square } from "lucide-react"
import { apiRequest } from "@/lib/api"
import { clearToken, getToken } from "@/lib/session"
import type { Encounter, Me, Previsit, Summary } from "@/lib/types"
import { AppShell } from "@/components/home/app-shell"
import { EmptyState, SectionHeading, StatusBadge, Toast } from "@/components/ui"
import styles from "@/app/home/clinical.module.css"

export function VisitWorkspace({encounterId}:{encounterId:string}){
  const router=useRouter();const [me,setMe]=useState<Me|null>(null);const [encounter,setEncounter]=useState<Encounter|null>(null);const [previsit,setPrevisit]=useState<Previsit|null>(null);const [notes,setNotes]=useState("");const [fasting,setFasting]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [recording,setRecording]=useState(false);const [confirmFinal,setConfirmFinal]=useState(false);const [summary,setSummary]=useState<Summary|null>(null);const [reasons,setReasons]=useState<Record<string,string>>({});const [notice,setNotice]=useState<{tone:"error"|"success"|"info";text:string}|null>(null);const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const chunks=useRef<Blob[]>([])
  const load=useCallback(async()=>{const profile=await apiRequest<Me>("/api/me");if(profile.role!=="DOCTOR")throw new Error("Only a clinic doctor can open a consultation.");const visit=await apiRequest<Encounter>(`/api/encounters/${encounterId}`);const context=await apiRequest<Previsit>(`/api/patients/${visit.patientId}/previsit`).catch(()=>null);setMe(profile);setEncounter(visit);setPrevisit(context);setFasting(Boolean(visit.fasting))},[encounterId])
  useEffect(()=>{if(!getToken()){router.replace("/login");return}const timer=window.setTimeout(()=>{void load().catch(error=>setNotice({tone:"error",text:error instanceof Error?error.message:"The visit could not be opened."}))},0);return()=>window.clearTimeout(timer)},[load,router])
  function signOut(){clearToken();router.replace("/login")}
  async function run(label:string,work:()=>Promise<void>){setBusy(label);setNotice(null);try{await work()}catch(error){setNotice({tone:"error",text:error instanceof Error?error.message:"That action could not be completed."})}finally{setBusy(null)}}
  function saveDraft(){if(!notes.trim()){setNotice({tone:"error",text:"Write or record the consultation notes first."});return}void run("draft",async()=>{const next=await apiRequest<Encounter>(`/api/encounters/${encounterId}/notes`,{method:"PUT",body:JSON.stringify({notes:notes.trim(),fasting})});setEncounter(next);setNotice({tone:"success",text:"The structured draft is ready for your review."})})}
  function runCheck(){void run("check",async()=>{const next=await apiRequest<Encounter>(`/api/encounters/${encounterId}/check`,{method:"POST"});setEncounter(next);setNotice({tone:next.openCriticalFindings?"info":"success",text:next.openCriticalFindings?"The check found a critical item that needs your written decision.":"Safety check complete. No open critical findings."})})}
  function overrideFinding(id:string){void run(id,async()=>{const next=await apiRequest<Encounter>(`/api/encounters/${encounterId}/findings/${id}/override`,{method:"POST",body:JSON.stringify({reason:reasons[id]?.trim()})});setEncounter(next);setNotice({tone:"success",text:"Your clinical reason was recorded in the audit log."})})}
  function finalise(){void run("final",async()=>{const next=await apiRequest<Encounter>(`/api/encounters/${encounterId}/finalise`,{method:"POST"});setEncounter(next);setConfirmFinal(false);const built=await apiRequest<Summary>(`/api/patients/${next.patientId}/summary`).catch(()=>null);setSummary(built);setNotice({tone:"success",text:"Visit finalised. The 30-day follow-up has started."})})}
  async function toggleRecording(){if(recorder.current){recorder.current.stop();return}try{stream.current=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const nextRecorder=new MediaRecorder(stream.current);recorder.current=nextRecorder;nextRecorder.addEventListener("dataavailable",event=>chunks.current.push(event.data));nextRecorder.addEventListener("stop",()=>{stream.current?.getTracks().forEach(track=>track.stop());recorder.current=null;setRecording(false);const blob=new Blob(chunks.current,{type:chunks.current[0]?.type||"audio/webm"});void run("audio",async()=>{const form=new FormData();form.append("audio",blob,"visit-notes.webm");const result=await apiRequest<{text:string}>(`/api/encounters/${encounterId}/audio`,{method:"POST",body:form});setNotes(current=>`${current.trim()}${current.trim()?"\n":""}${result.text}`);setNotice({tone:"success",text:"Transcription added. Check it carefully before drafting."})})});nextRecorder.start();setRecording(true);setNotice({tone:"info",text:"Listening now. Press stop when you have finished."})}catch{setNotice({tone:"error",text:"The microphone is blocked. Allow browser access or type the notes instead."})}}
  if(!me||!encounter)return <main className={styles.clinicalLoading}><LoaderCircle size={24}/><p>{notice?.text||"Preparing the consultation…"}</p><Link className="button-secondary" href="/home">Back to home</Link></main>
  const final=encounter.status==="FINAL";const draftReady=Boolean(encounter.diagnosis||encounter.plan||encounter.prescription.length);const gate=final?"This report is final.":!draftReady?"Draft the report first.":!encounter.checked?"Run the safety check on this version.":encounter.openCriticalFindings?`${encounter.openCriticalFindings} critical finding${encounter.openCriticalFindings===1?"":"s"} still need a written reason.`:null
  return <AppShell me={me} onSignOut={signOut}>{notice&&<Toast tone={notice.tone} onClose={()=>setNotice(null)}>{notice.text}</Toast>}<main className={styles.visit}><div className={styles.visitTop}><Link href={`/home/patients/${encounter.patientId}`}><ArrowLeft size={16}/>Back to patient</Link><div><span className={styles.liveDot}/><p>{final?"Final report":"Consultation in progress"}</p></div></div><section className={styles.visitIdentity}><div><p>Today’s consultation</p><h1>{previsit?.patient.fullName||"Patient visit"}</h1><span>{previsit?.patient.preferredLanguage.toUpperCase()} · Encounter {encounter.id.slice(0,8)}</span></div><StatusBadge level={final?"ok":"review"}>{final?"Final":"Draft"}</StatusBadge></section>
    <div className={styles.visitGrid}><section className={styles.notesCard}><SectionHeading eyebrow="Step 1" title="Capture the consultation" action={<button className={recording?"button-danger":"button-secondary"} disabled={final||busy==="audio"} onClick={()=>void toggleRecording()}>{recording?<><Square size={15}/>Stop recording</>:<><Mic size={16}/>Speak notes</>}</button>}/><p className={styles.clinicalIntro}>Use normal clinical shorthand. Transcribed speech is never saved until you review it and draft the report.</p><textarea value={notes} onChange={event=>setNotes(event.target.value)} disabled={final} rows={11} placeholder={"Diagnosis: T2DM, BP stable\nT. Metformin 500 mg BD PC\nPlan: continue, review 2/52"}/><label className={styles.fastingCheck}><input type="checkbox" checked={fasting} disabled={final} onChange={event=>setFasting(event.target.checked)}/><span><strong>Patient is fasting</strong>Adjust medicine timing for Ramadan in the summary.</span></label><button className="button-primary" disabled={final||busy==="draft"} onClick={saveDraft}><Sparkles size={16}/>{busy==="draft"?"Drafting…":"Turn notes into draft"}</button></section>
      <aside className={styles.previsitAside}><SectionHeading eyebrow="At a glance" title="Pre-visit context"/><div className={styles.contextBlock}><h3>Reason</h3><p>{previsit?.intake?.report?.reason||"No intake report"}</p></div><div className={styles.contextBlock}><h3>Allergies</h3><div>{previsit?.patient.allergies?.length?previsit.patient.allergies.map(item=><StatusBadge level="red" key={item}>{item}</StatusBadge>):<span>None recorded</span>}</div></div><div className={styles.contextBlock}><h3>Everything they take</h3>{previsit?.medications.slice(0,5).map(med=><p key={med.id}><PillIcon/>{med.name}</p>)}{!previsit?.medications.length&&<span>Nothing listed</span>}</div></aside>
    </div>
    <section className={styles.draftCard}><SectionHeading eyebrow="Step 2" title="Review the structured draft" action={<button className="button-secondary" disabled={!draftReady||final||busy==="check"} onClick={runCheck}><ShieldAlert size={16}/>{busy==="check"?"Checking…":"Run safety check"}</button>}/>{draftReady?<div className={styles.draftGrid}><div><small>Diagnosis</small><p>{encounter.diagnosis||"Not written"}</p></div><div><small>Plan</small><p>{encounter.plan||"Not written"}</p></div><div><small>Follow-up</small><p>{encounter.followUp||"Not written"}</p></div><div className={styles.rxBlock}><small>Prescription</small>{encounter.prescription.length?<table><thead><tr><th>Medicine</th><th>Strength</th><th>Dose</th><th>Times/day</th><th>Timing</th></tr></thead><tbody>{encounter.prescription.map((line,index)=><tr key={index}><td>{line.name||line.raw}</td><td>{line.strengthMg?`${line.strengthMg} mg`:"—"}</td><td>{line.unitsPerDose??"—"}</td><td>{line.asNeeded?"PRN":line.timesPerDay??"—"}</td><td>{line.timing?.replaceAll("_"," ")||"—"}</td></tr>)}</tbody></table>:<p>No medicines in these notes.</p>}</div></div>:<EmptyState icon={<FileText size={20}/>} title="No draft yet" copy="Write the consultation notes above, then ask Khabar to structure them for your review."/>}</section>
    <section className={styles.safetyCard}><SectionHeading eyebrow="Step 3" title="Resolve the safety check"/>{!encounter.checked?<EmptyState icon={<ShieldAlert size={20}/>} title="Not checked yet" copy="Run the check after reviewing the structured draft. Editing the notes makes an older check out of date."/>:encounter.findings.length?encounter.findings.map(finding=><article key={finding.id} className={finding.severity==="CRITICAL"?styles.criticalFinding:styles.reviewFinding}><span>{finding.severity==="CRITICAL"?<AlertTriangle size={19}/>:<HeartPulse size={19}/>}</span><div><div><StatusBadge level={finding.severity==="CRITICAL"?"red":"watch"}>{finding.check.replaceAll("_"," ")}</StatusBadge>{finding.overrideReason&&<StatusBadge level="ok">Reason recorded</StatusBadge>}</div><p>{finding.detail}</p>{finding.overrideReason?<blockquote>{finding.overrideReason}</blockquote>:finding.severity==="CRITICAL"&&!final?<div className={styles.overrideBox}><label>Why is it clinically safe to proceed?<textarea rows={2} value={reasons[finding.id]||""} onChange={event=>setReasons({...reasons,[finding.id]:event.target.value})} placeholder="At least 10 characters; saved in the audit log."/></label><button className="button-secondary" disabled={(reasons[finding.id]?.trim().length||0)<10||busy===finding.id} onClick={()=>overrideFinding(finding.id)}>Record reason</button></div>:null}</div></article>):<div className={styles.allClear}><CheckCircle2 size={23}/><div><strong>No safety problems found</strong><p>The current draft has passed the configured checks.</p></div></div>}</section>
    <section className={`${styles.finalGate} ${!gate?styles.gateReady:""}`}><div><span>{gate?<ShieldAlert size={23}/>:<CheckCircle2 size={23}/>}</span><div><p>Final clinical gate</p><h2>{gate||"Ready to finalise and begin follow-up."}</h2><small>Finalising sends the patient summary and starts the 30-day follow-up.</small></div></div>{!final&&(confirmFinal?<div className={styles.confirmFinal}><p>Confirm that you reviewed this report and its safety result.</p><button className="button-secondary" onClick={()=>setConfirmFinal(false)}>Go back</button><button className="button-primary" disabled={Boolean(gate)||busy==="final"} onClick={finalise}>{busy==="final"?"Finalising…":"Confirm final report"}</button></div>:<button className="button-primary" disabled={Boolean(gate)} onClick={()=>setConfirmFinal(true)}>Review and finalise</button>)}</section>
    {summary&&<section className={styles.summaryResult}><span><Check size={20}/></span><div><p>Patient-facing summary</p><blockquote>{summary.text}</blockquote>{summary.needsDoctor&&<small>Needs clinician advice: {summary.needsDoctor}</small>}</div></section>}
  </main></AppShell>
}

function PillIcon(){return <span aria-hidden="true">•</span>}
