-- Follow-up cases: a patient's need for a person to follow up, from listing to a closure with a reason,
-- with an append-only history. One open case per patient, enforced by the unique open_key.
create table follow_up_case (
    id uuid not null primary key,
    clinic_id uuid not null,
    patient_id uuid not null,
    status varchar(255) not null check (status in ('NEW','ASSIGNED','ACKNOWLEDGED','IN_PROGRESS','ESCALATED','UNABLE_TO_CONTACT','RESOLVED')),
    level varchar(255) not null check (level in ('RED','WATCH','REVIEW','OK')),
    reason varchar(20) not null,
    open_key varchar(80) unique,
    owner_id uuid,
    opened_at timestamp(6) with time zone not null,
    acknowledged_at timestamp(6) with time zone,
    escalated_at timestamp(6) with time zone,
    escalated_to uuid,
    contact_attempts integer not null,
    last_attempt_at timestamp(6) with time zone,
    closed_at timestamp(6) with time zone,
    closed_by uuid,
    closure_reason varchar(255) check (closure_reason in ('CONTACTED_NO_FURTHER_ACTION','ADVICE_GIVEN_PER_PROTOCOL','APPOINTMENT_ARRANGED','DOCTOR_REVIEWED','REFERRED_TO_EMERGENCY_CARE','UNABLE_TO_CONTACT_AFTER_ATTEMPTS','DUPLICATE_OR_FALSE_ALARM','CONTACT_RECORDED')),
    closure_note_enc varchar(4096),
    constraint fk_case_clinic foreign key (clinic_id) references clinic,
    constraint fk_case_patient foreign key (patient_id) references patient,
    constraint ck_case_closed check ((closed_at is null and open_key is not null) or (closed_at is not null and open_key is null and closure_reason is not null))
);
create index ix_case_clinic_closed on follow_up_case (clinic_id, closed_at);

create table follow_up_case_event (
    id bigint generated by default as identity primary key,
    case_id uuid not null,
    action varchar(255) not null check (action in ('OPENED','LEVEL_RAISED','ASSIGNED','ACKNOWLEDGED','CONTACT_REACHED','CONTACT_NO_ANSWER','ESCALATED','CLOSED')),
    from_status varchar(255) check (from_status in ('NEW','ASSIGNED','ACKNOWLEDGED','IN_PROGRESS','ESCALATED','UNABLE_TO_CONTACT','RESOLVED')),
    to_status varchar(255) not null check (to_status in ('NEW','ASSIGNED','ACKNOWLEDGED','IN_PROGRESS','ESCALATED','UNABLE_TO_CONTACT','RESOLVED')),
    actor_id uuid,
    actor_label varchar(255) not null,
    note_enc varchar(4096),
    at timestamp(6) with time zone not null,
    constraint fk_case_event_case foreign key (case_id) references follow_up_case
);
create index ix_case_event_case on follow_up_case_event (case_id);

-- What each clinic has decided: hours, escalation contact, acknowledgement times, and the weekly rota.
create table clinic_settings (
    clinic_id uuid not null primary key,
    hours varchar(200),
    escalation_contact varchar(200),
    red_ack_minutes integer not null,
    watch_ack_minutes integer not null,
    review_ack_minutes integer not null,
    updated_at timestamp(6) with time zone,
    updated_by uuid,
    constraint fk_settings_clinic foreign key (clinic_id) references clinic
);

create table rota_entry (
    id uuid not null primary key,
    clinic_id uuid not null,
    day_of_week varchar(255) not null check (day_of_week in ('MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY')),
    primary_user_id uuid not null,
    backup_user_id uuid,
    constraint uk_rota_clinic_day unique (clinic_id, day_of_week),
    constraint fk_rota_clinic foreign key (clinic_id) references clinic,
    constraint fk_rota_primary foreign key (primary_user_id) references app_user,
    constraint fk_rota_backup foreign key (backup_user_id) references app_user
);

-- Administrative and follow-up actions for clinic administrators. Subjects never name a patient.
create table clinic_activity (
    id bigint generated by default as identity primary key,
    clinic_id uuid not null,
    actor_id uuid not null,
    actor_label varchar(255) not null,
    action varchar(255) not null check (action in ('STAFF_INVITED','STAFF_REVOKED','SETTINGS_UPDATED','CASE_ASSIGNED','CASE_ACKNOWLEDGED','CASE_CONTACT_ATTEMPT','CASE_ESCALATED','CASE_CLOSED')),
    subject varchar(255) not null,
    at timestamp(6) with time zone not null,
    constraint fk_activity_clinic foreign key (clinic_id) references clinic
);
create index ix_clinic_activity_clinic on clinic_activity (clinic_id);
